---
output: pdf_document
params: 
    screening.type: ""
    screening.data: data.frame()
    label.months: 2
    
title: "`r params$screening.type` Report" 

classoption: landscape

---



```{r parameterizedRmarkdownCode, eval = FALSE, include = FALSE}
#used to run rmarkdown with parameters 
rmarkdown::render("cancer_report.Rmd", params = list(
  screening.type = "Colorectal Cancer Screening",
  screening.data = clean_data,  
  label.months = 3
))
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.show="hold", out.width="50%", message = FALSE, warning = FALSE)
library(shiny)
library(tidyverse)
library(readxl)
library(gridExtra)
library(patchwork)
library(shinyFiles)
library(directlabels)
library(colorspace)

# setting up axes for plots - note: titles of plots based on params$screening.type
 ax.date = expression(atop(bold("Date"), "   "))
 ax.screening = expression(atop("   ", bold("Screening Rate (%)")))
 ax.patients = "Number of Patients"
 ax.location = "Site"
 
 # create variable for title of All patients plots
   if(params$screening.type == "Colorectal Cancer Screening"){
     title.patients = "Patients 50-75 Years Old"
   }else if(params$screening.type == "Cervical Cancer Screening"){
     title.patients = "Female Patients 21-64 Years Old"
   }else if(params$screening.type == "Mammogram"){
     title.patients = "Female Patients 50-74 Years Old"
   }
 
 # set plot options for all plots to abide by
 plot_options = theme(axis.text=element_text(size=12),
                      axis.title=element_text(size=14,face="bold"),
                      plot.title = element_text(size = 14, face = "bold"),
                      legend.text = element_text(size=12),
                      legend.title = element_text(size=14, face = "bold"))

margin_val = 2.5
plot_colors = darken(c("#000000", "#80CDC1", "#B8E186", "#9fb88c", "#92C5DE", "#DFC27D", "#FDB863",  "#EA9999", "#7686c4", "#D5A6BD", "#A2C4C9", "#D5A6BD", "#F4A582"))

```

```{r plotFunctions, include = FALSE}
# creates screening line plot for a specific location
# inputs:
#      df - dataframe with full cleaned data (including all locations)
#      loc - string of location name
#      ymin - y axis minimum value
#      ymax - y axis max value
create_screening_plot = function(df, loc, ymin, ymax,  mycolor = "grey"){
  df%>%filter(location == loc)%>%
    ggplot(aes(x = date, y = screening_rate))+
    geom_line(size = 1.5, color = mycolor)+
    theme_bw()+
    guides(size = FALSE)+
    labs(x = ax.date, y = "Number of Patients")+
    ylim(ymin, ymax)+
    labs(x = ax.date, y = ax.screening)+
    ggtitle(paste(loc, params$screening.type, "Rate"))+
    plot_options+
    scale_x_date(date_labels = "%b %Y")
}

# creates screening line plot for a specific location
# inputs:
#      df - dataframe with full cleaned data (including all locations)
#      loc - string of location name
#      ymax - y axis max value
create_patient_barplot = function(df, loc, ymax,  mycolor = "grey"){
  df%>%filter(location == loc)%>%
    ggplot(aes(x = date, y = all_patients))+
    geom_bar(stat = "identity", fill = mycolor)+
    theme_bw()+
    labs(x = ax.date, y = ax.patients)+
    ggtitle(paste(loc, title.patients))+
    plot_options+
    ylim(0, ymax)+
    scale_x_date(date_labels = "%b %Y")
}

```

```{r CreateNotes, include = FALSE}
# create notes on patients included in "All patients" and screening rates
notes = "No notes on patients for selected screening type." 
if(params$screening.type == "Colorectal Cancer Screening"){
     notes = paste("Notes on patient data: ","","All patients: ","Active patients between 50 and 75 years of age that DO NOT have colorectal cancer that had a
medical visit during the 3 years prior to the end of the reporting period. ", "",
                 "Screened patients: ", "Patients that received Colonscopy in the last 10 years; Fecal Immunochemical Test (FIT)
in the last 1 year; Fecal Occult Testing (FOBT) in the 1  year; or FIT DNA in the last 3 years.", " "," ",sep = "\n")

   }else if(params$screening.type == "Cervical Cancer Screening"){
     notes = paste("Notes on patient data: ","","All patients: ", "Active Female patients between 21 and 64 years that had a visit during the 3 years prior
to the end of the reporting period and that DID  NOT received a hysterectomy. ", "",
                 "Screened patients:", "Active Female patients between 21 and 29 years that had a cevical cancer screening within
the last 3 years or active female patients between 30 and 64 years old that had a cervical cancer
screening within the last 5 years.", " "," ",sep = "\n")
   }else if(params$screening.type == "Mammogram"){
     notes = paste("Notes on patient data: ","","All patients: ", "Active Female patients between the 50 and 74 years of age that DID NOT have a mastectomy and
that  had a medical visit during the 3 years prior to the end of the reporting period. ","",
                 "Screened patients: ", "Patients that received a mammogram during the 2 years prior to the end of the reporting period.", " ", " ",sep = "\n")

   }
```


<!-- Output patient notes -->
`r notes` 

```{r, echo = FALSE, fig.height=1}
ggplot(data = NULL)+ theme_void()
```

```{r allSitesBarplot, include = FALSE}
date_summary = params$screening.data%>%summarize(min_date = min(date), max_date = max(date))   # determine first and last dates plotted

    p1= params$screening.data%>%filter(location == "All")%>%
      ggplot(aes(x = date, y = all_patients))+
      geom_bar(stat = "identity")+
      theme_bw()+
      labs(x = ax.date, y = ax.patients)+
      ggtitle(paste("PCHS", title.patients))+
      plot_options+
      scale_x_date(date_labels = "%b %Y")
```
```{r allSitesLineplot, include = FALSE}
    # create plot
    p2= params$screening.data%>%
      ggplot(aes(x = date, y = screening_rate, color = location))+
      geom_line(data = params$screening.data%>%filter(location == "All"), color = "grey", size = 10, alpha = 0.5)+   # plot shadow around "All" (behind other lines)
      geom_point(aes())+ # plot points for all sites
      geom_line(aes(), size = 1.5)+ # plot lines for all sites
      geom_line(data = params$screening.data%>%filter(location == "All"), color = "black", size = 1.5)+   # plot "All" on top of other lines
      #xlim(date_summary$min_date, date_summary$max_date + months(8))+   # change x axis lims?
      #annotate("text", x = annotation$date + months(1), y = annotation$screening_rate, label = "  ", size = 10)+   # annotation for avg. rate
      theme_bw()+
      guides(size = FALSE, color = FALSE)+   # don't include legend for size of dots
      labs(x = ax.date, y = ax.screening, color = ax.location)+
      ggtitle(paste("PCHS",params$screening.type, "Rates"))+
      plot_options+
      scale_x_date(#date_breaks = "3 months",
                   date_labels = "%b %Y",
                   #labels=date_format("%b-%Y"),
                   #limits = c(date_summary$min_date,date_summary$max_date + weeks(6)))+ #extend xlim so labels aren't cut off
                  limits = c(date_summary$min_date,date_summary$max_date + months(params$label.months)))+ #extend xlim so labels aren't cut off
     geom_dl(aes(label = location), method = list(dl.trans(x = x + .3), "last.qp", cex = 1.2, fontface = "bold")) +
      #scale_color_brewer(palette = "Set3")
      scale_color_manual(values = plot_colors)
      #geom_dl(aes(label = location), method = list(dl.combine("last.points")), cex = 0.8)


    #%>%
    #  direct.label("last.qp")

    #Levels: All Alma Illery Braddock CHC East End Hazelwood Hill House McKeesport Steel Valley West End Wilkinsburg

    # # margin of white space between plots
    # margin = theme(plot.margin = unit(rep(1, times = 2), "cm"))
    # grid.arrange(grobs = lapply(p1, "+", margin), nrow = 1, widths = c(1.5,2))  # output plot
    # grid.arrange(grobs = p1, nrow = 1, widths = c(1.5,2))  # output plot
```

<!-- # Graphs for all PCHS sites -->
```{r outputAllSitesPlots, echo = FALSE}
print(p1)
print(p2)
```

<!-- # Graphs for individual sites -->
```{r plotIndividualSites, echo = FALSE}
# find max number of patients
    max_patients = params$screening.data%>%filter(location != "All")%>%group_by(location)%>%summarize(max_patients_loc = max(all_patients))%>%filter(max_patients_loc == max(max_patients_loc))
    max_patients = max_patients$max_patients_loc

    # find max range of screening rates for single location
    temp_data = params$screening.data%>%filter(location!="All")%>%group_by(location)%>%
      summarize(rate_range = max(screening_rate)- min(screening_rate),   # find ranges of screening rates for each location
                middle_rate = min(screening_rate) + 0.5 * rate_range)    # find middle between max and min screening rate for each locaiton
    max_range = temp_data%>%filter(rate_range == max(rate_range)) # calculate max range
    max_range = max_range$rate_range                              # isolate max range as a number
    y_ranges = temp_data%>%mutate(ymin = middle_rate - 0.5 * max_range, ymax = middle_rate + 0.5 * max_range)  # create new ranges for y axes


    nLocations = length(unique(params$screening.data$location))    # get number of locations in dataset
    p3 = list()   # initialize list of all patients bar graph

    # for each location, create both plots
    for( i in 1:(nLocations-1)){

      location_i = params$screening.data$location[i]                   # get name of ith location

      # create all patient bar graph
      p1 = create_patient_barplot(params$screening.data, location_i, max_patients, plot_colors[i+1])#+scale_fill_manual(values = c(plot_colors[i+1], "black"))
      #create screening rate line plots
      p2 = create_screening_plot(params$screening.data, location_i, y_ranges$ymin[i], y_ranges$ymax[i], plot_colors[i+1])#+scale_color_manual(values = c(plot_colors[i+1], "black"))

      print(p1)
      print(p2)
    }
```

